openapi: 3.0.1
info:
  title: Example API
  description: This is an example API
  version: '1.0'
servers:
  - url: https://apim-apiops.azure-api.net/myapi
paths:
  /hello:
    get:
      summary: Hello World
      description: Hello World
      operationId: helloWorld
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
              example: string
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]